[custom]

# 规则组
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Direct/Direct.list
ruleset=⛔ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🔰 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/eming0802/rules/refs/heads/main/rule/china.list
ruleset=🕹️ 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
ruleset=🕹️ 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.list
ruleset=🎮 蒸汽平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🕹️ 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list
ruleset=🍎 苹果服务https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=Ⓜ️ 微软服务https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=📀 Emby媒体,https://raw.githubusercontent.com/eming0802/rules/refs/heads/main/rule/Emby.list
ruleset=🎯 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=🎯 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Cloud/CloudCN/CloudCN.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.list
ruleset=🐼 国内直连,[]GEOSITE,CN
ruleset=🐼 国内直连,[]GEOIP,CN
ruleset=🎈 漏网之鱼,[]FINAL

# 策略组
custom_proxy_group=🎯 节点选择`select`[]♻️ 自动选择`[]🌏 全球节点`.*(新加坡|狮城|獅城|SG|(?i)Singapore|香港|HK|(?i)Hong|日本|JP|(?i)Japan|台湾|台灣|TW|(?i)Taiwan)
custom_proxy_group=♻️ 自动选择`url-test`(?=.*(新加坡|狮城|獅城|SG|(?i)Singapore|香港|HK|(?i)Hong|日本|JP|(?i)Japan|台湾|台灣|TW|(?i)Taiwan))^((?!(3.0x)).)*$`http://www.gstatic.com/generate_204`600,,0
custom_proxy_group=🌏 全球节点`select`.*^(.(?!(新加坡|狮城|獅城|SG|(?i)Singapore|香港|HK|(?i)Hong|日本|JP|(?i)Japan|台湾|台灣|TW|(?i)Taiwan)))*$
custom_proxy_group=🎮 蒸汽平台`select`[]🎯 节点选择`[]♻️ 自动选择`[]🌏 全球节点
custom_proxy_group=🕹️ 游戏平台`select`[]🎯 节点选择`[]♻️ 自动选择`[]🌏 全球节点`[]DIRECT
custom_proxy_group=📀 Emby媒体`select`[]🎯 节点选择`[]♻️ 自动选择`[]🌏 全球节点`[]DIRECT`.*(Emby)
custom_proxy_group=🎈 漏网之鱼`select`[]🎯 节点选择`[]♻️ 自动选择`[]🌏 全球节点`[]DIRECT
custom_proxy_group=🐼 国内直连`select`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT
custom_proxy_group=⛔ 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🔰 应用净化`select`[]REJECT`[]DIRECT

# 设置
enable_rule_generator=true
overwrite_original_rules=true
exclude_remarks=(距离|重置|过期|到期|剩余)