[custom]

# 规则组
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Direct/Direct.list
ruleset=⛔ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🔰 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/eming0802/rules/refs/heads/main/rule/china.list
ruleset=🕹️ 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
ruleset=🕹️ 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.list
ruleset=🎮 蒸汽平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🕹️ 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list
ruleset=📀 Emby媒体,https://raw.githubusercontent.com/eming0802/rules/refs/heads/main/rule/Emby.list
ruleset=🎯 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=🎯 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Cloud/CloudCN/CloudCN.list
ruleset=🐼 国内直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
ruleset=🐼 国内直连,[]GEOIP,CN
ruleset=🐼 国内直连,[]GEOSITE,CN
ruleset=🎈 漏网之鱼,[]FINAL

# 策略组
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`(?=.*(新加坡|狮城|獅城|SG|(?i)Singapore|香港|HK|(?i)Hong|日本|JP|(?i)Japan|台湾|台灣|TW|(?i)Taiwan))^((?!(3.0x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌏 全球节点`select`.*^(.(?!(新加坡|狮城|獅城|SG|(?i)Singapore|香港|HK|(?i)Hong|日本|JP|(?i)Japan|台湾|台灣|TW|(?i)Taiwan)))*$
custom_proxy_group=📀 Emby媒体`select`[]🎯 节点选择`[]♻️ 自动选择`[]🌏 全球节点`[]DIRECT`.*(Emby)
custom_proxy_group=🎮 蒸汽平台`select`[]🎯 节点选择`[]♻️ 自动选择`[]🌏 全球节点
custom_proxy_group=🕹️ 游戏平台`select`[]🎯 节点选择`[]♻️ 自动选择`[]🌏 全球节点`[]DIRECT
custom_proxy_group=🎈 漏网之鱼`select`[]🎯 节点选择`[]♻️ 自动选择`[]🌏 全球节点`[]DIRECT
custom_proxy_group=🐼 国内直连`select`[]DIRECT
custom_proxy_group=⛔ 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🔰 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50

# 设置
enable_rule_generator=true
overwrite_original_rules=true
exclude_remarks=(距离|重置|过期|到期|剩余)
